Django_Password_Helmi/urls.py
# from django.conf.urls import url,include
from django.contrib import admin
from django.urls import path, include
from basic_app import views

urlpatterns = [
    path('',views.index,name='index'),
    path('admin/', admin.site.urls),
    # url(r'^admin/', admin.site.urls),
    path('basic_app/',include('basic_app.urls')),
    path('logout/',views.user_logout,name='logout'),
    # url(r'^login/',views.user_login,name='user_login'),
]

basic_app/urls.py
from django.urls import path
from basic_app import views

app_name = 'basic_app'
urlpatterns = [
    path ('register/',views.register,name='register'),
    path ('user_login/',views.user_login,name='user_login'),
]

basic_app/models.py
from distutils.command.upload import upload
from django.db import models
from django.contrib.auth.models import User


# Create your models here.


class UserProfileInfo(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    portfolio_site = models.URLField(blank=True)
    profile_pic = models.ImageField(upload_to='profile_pics', blank=True)

    def __str__ (self):
        return self.user.username

basic_app/forms.py
from django import forms
from django.contrib.auth.models import User
from basic_app.models import UserProfileInfo
from django.views.generic import TemplateView, FormView
from django.contrib.auth import password_validation


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput,
                                help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Password confirmation', widget=forms.PasswordInput)
    def clean(self):
        if self.cleaned_data.get('password') != self.cleaned_data.get('password2'):
            raise forms.ValidationError('Password are not equal')
        password_validation.validate_password(self.cleaned_data.get('password'), None)
        return self.cleaned_data

    class Meta():
        model = User
        fields = ('username','email','password')

class UserProfileInfoForm(forms.ModelForm):
    class Meta():
        model = UserProfileInfo
        fields = ('portfolio_site','profile_pic')

basic_app/views.py
from django.shortcuts import render

# Create your views here.
from django.shortcuts import render
from basic_app.forms import UserForm,UserProfileInfoForm

from django.contrib.auth import authenticate,login,logout 
from django.http import HttpResponseRedirect, HttpResponse
from django.urls import reverse 
from django.contrib.auth.decorators import login_required

from basic_app.models import UserProfileInfo 

# Create your views here.
def index(request):
#     if request.user.is_authenticated:
#         dt = UserProfileInfo.objects.filter(user=request.user.id).first()
#         data = {
#             'profil_pics': dt
#         }
#         return render(request,'basic_app/index.html',data)
#     # print(dt.foto_profil)
    return render(request,'basic_app/index.html')




def register(request):

    registered = False

    if request.method == "POST":
        user_form = UserForm (data=request.POST)
        profile_form = UserProfileInfoForm (data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():

            user = user_form.save ()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'profile_pic' in request.FILES:
                profile.profile_pic = request.FILES ['profile_pic']

            profile.save()

            registered =True

        else :
            print(user_form.errors,profile_form.errors)
    else :
        user_form = UserForm()
        profile_form = UserProfileInfoForm()
    return render (request,'basic_app/registrasi.html',
                    {'user_form':user_form,
                    'profile_form':profile_form,
                    'registered':registered})

def user_login(request):

    if request.method=='POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(username=username,password=password)

        if user:
            if user.is_active:
                login(request,user)
                return HttpResponseRedirect(reverse('index'))
            else:
                return HttpResponse("Akun tidak aktif")
        else:
            print("Seseorang berusaha login tapi tidak berhasil")
            print("Username: {} and password {}".format(username,password))
            return HttpResponse("invalid data login") 
    else:
        return render(request,'basic_app/login.html',{})

@login_required
def user_logout(request):
    logout(request)
    return HttpResponseRedirect(reverse('index'))

templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <link rel="stylesheet" href="">
    <head>
        
            {% if messages %}
                {% for message in messages %}
                    alert(message);
                {% endfor %}
            {% endif %}
       
        <meta charset="UTF-8">
        <title></title>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    </head>
    <body>
        <nav class = 'navbar navbar-default navbar-static-top'>
            <div class ="container">
                <ul class = "nav navbar-nav">
                    <li><a class="navbar-brand" href="{% url 'index' %}">Home Page</a></li>
                    <li><a class="navbar-link" href="{% url 'admin:index' %}">Admin</a></li>
                    <li><a class="navbar-link" href="{% url 'basic_app:register' %}">Registrasi</a></li>
                
                {% if user.is_authenticated %}
                    <li><a class="navbar-link" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}
                    <li><a class="navbar-link" href="{% url 'basic_app:user_login' %}">Login</a></li>

                {% endif %}
                </ul>
            </div>
        </nav>
        
        
    
        <div class="container">
            {% block body_block%}
            {% endblock%}
        </div>
    </body>
</html>

templates/basic_app/index.html
{% extends "basic_app/base.html" %}
{% block body_block %}

<div class="jumbotron">
    <h1> Ini adalah Halaman Index Geissss </h1>
    
    {% if user.is_authenticated %}
    <h1>Selamat datang</h1>
        <h2>Hello {{ user.username }}</h2><br>
    {% else %}
    <h1>Selamat datang !</h1>
        <h2>Silahkan Login atau Register.</h2>
    {% endif %}
</div>

{% endblock %}

templates/basic_app/login.html
{% extends 'basic_app/base.html' %}
{% load static %}

{% block body_block %}

<div class="container">
        <h1> Silahkan Login</h1>
       
        <!-- <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p}}
            <input type="submit" name="" value="Register">

        </form> -->

       
        <form method="post" action="{% url 'basic_app:user_login' %}">
            {% csrf_token %}
    
            <label for="username">Username:</label>
            <input type="text" name="username" placeholder="Username"><label for="password">Password:</label>
            <input type="password" name="password" placeholder="Password"><input type="submit" name="" value="Login"></form></div>
        

</div>

{% endblock %}

templates/basic_app/registrasi.html
{% extends 'basic_app/base.html' %}
{% load static %}

{% block body_block %}

<div class="jumbotron">
    {% if registered %}
        <h1>Terimakasih Telah Melakukan Registrasi</h1>
    {% else %}
        <h1> Silahkan Registrasi Disini</h1>
        <h3>Isi Form Dibawah Ini</h3>

        <form enctype="multipart/form-data" method="post">
            {% csrf_token %}
            {{ user_form.as_p }}
            {{ profile_form.as_p}}
            <input type="submit" name="" value="Register">

        </form>
        
{% endif %}
</div>

{% endblock %}